apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-pvc
  namespace: image-processor
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi